name: Deploy to AWS ECS

on:
  push:
    branches:
     - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION}}
  REPO_NAME: nest-app-repo-docker-course
  AWS_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY}}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY
          docker build -t $REPO_NAME:$IMAGE_TAG .
          docker tag $REPO_NAME:$IMAGE_TAG $AWS_REGISTRY/$REPO_NAME:$IMAGE_TAG
          docker push $AWS_REGISTRY/$REPO_NAME:$IMAGE_TAG


      