name: Deploy to AWS ECS

on:
  push:
    branches:
     - main

env:
  REPO_NAME: nest-app-repo-docker-course

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to ECR
        id: build-image
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY}}
          docker build -t $REPO_NAME:${{ github.sha }} .
          docker tag $REPO_NAME:${{ github.sha }} ${{ secrets.AWS_ECR_REGISTRY}}/$REPO_NAME:${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_REGISTRY}}/$REPO_NAME:${{ github.sha }}


      